baseURL = "https://piotrromanowski.github.io/"
languageCode = 'en-us'
title = 'Piotr'
theme = 'holy'

[menu]

  [[menu.main]]
    identifier = "rss"
    name = "rss"
    url = "/index.xml"
    weight = 10
